# Continuous integration with travis
language: r
sudo: required

r:
 - release
 - devel

# cache packages to speed up builds
cache: packages

r_packages:
 - covr
 - ggplot2
 - ggfortify
 - testthat
 - assertthat
 - raster
 - sp 
 - reshape2

r_github_packages:
 - andrewzm/INLA

after_success:
 - Rscript -e 'library(covr);codecov()'


matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
    - r: devel
      r_github_packages: andrewzm/INLA
    - r: release
    - r: devel
