# Continuous integration with travis
language: r
sudo: required

r:
 - release
 - devel

# cache packages to speed up builds
cache: packages

r_packages:
 - covr
 - ggplot2

before_script:
- Rscript -e "install.packages(\"INLA\", repos=\"https://www.math.ntnu.no/inla/R/stable\")"



after_success:
 - Rscript -e 'library(covr);codecov()'
