# Continuous integration with travis
language: r
sudo: required



# cache packages to speed up builds
#cache: packages

r_packages:
 - covr
 - ggplot2
 - ggfortify
 - testthat
 - assertthat
 - raster
 - sp 
 - reshape2

after_success:
 - Rscript -e 'library(covr);codecov()'


matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
      os: linux
    - r: devel
      r_github_packages: andrewzm/INLA
      os: linux
    - r: devel
      os: osx

